# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 334457eb3ae9d72d3b7b27434799a1017273a0ed1a46a5dfcfc6b8f8ea5cd68e6995d4099bc98a548d43f5fdc7071afaaef9741aa58f759f58bf5f072d9200db

test:
  secret_key_base: a2f048f687fb860147b414abf291a2b174e7b202947d2bc5615cd7769ba1d6e6e36ab6156183970d7c211f9a5869b54f687beaa31bccb38c7b20822d63cd8424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
